// frontend/src/routes/register/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import type { ActionData, PageData } from './$types';

	let { data, form }: { data: PageData; form: ActionData } = $props();
</script>

<svelte:head><title>Register · AthletOS</title></svelte:head>

<main class="mx-auto max-w-sm space-y-4 p-4">
	<h1 class="text-2xl font-bold">Register</h1>

	{#if form?.message}
		<p class="alert alert-error" role="alert">{form.message}</p>
	{/if}

	<form method="POST" class="space-y-3">
		<label class="form-control block">
			<span class="label-text">Name</span>
			<input
				name="display_name"
				autocomplete="name"
				required
				value={form?.displayName ?? ''}
				class="input-bordered input w-full"
			/>
		</label>

		<label class="form-control block">
			<span class="label-text">Email</span>
			<input
				name="email"
				type="email"
				autocomplete="email"
				required
				value={form?.email ?? ''}
				class="input-bordered input w-full"
			/>
		</label>

		<label class="form-control block">
			<span class="label-text">Password</span>
			<input
				name="password"
				type="password"
				autocomplete="new-password"
				required
				class="input-bordered input w-full"
			/>
			<span class="label-text-alt">
				There is no password reset in v1. Keep this somewhere you can find it.
			</span>
		</label>

		<button class="btn w-full btn-primary" type="submit">Create account</button>
	</form>

	<p class="text-sm">
		Already registered? <a
			class="link"
			href={data.from ? resolve(`/login?from=${encodeURIComponent(data.from)}`) : resolve('/login')}
			>Sign in</a
		>
	</p>
</main>

// resources/js/pages/auth/register.tsx
import { Head, Link, useForm } from '@inertiajs/react';
import { FormEventHandler } from 'react';
import AuthLayout from '@/layouts/auth-layout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { register, login } from '@/routes';

interface RegisterData {
  name: string;
  email: string;
  password: string;
  password_confirmation: string;
}

export default function Register() {
  const { data, setData, post, processing, errors, reset } = useForm<RegisterData>({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
  });

  const submit: FormEventHandler = (e) => {
    e.preventDefault();

    post(register.url(), {
      onFinish: () => reset('password', 'password_confirmation'),
    });
  };

  return (
    <AuthLayout title="Register">
      <Head title="Register" />

      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md border border-gray-200 dark:border-gray-700 overflow-hidden">
        <div className="p-6">
          <div className="text-center mb-6">
            <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-100">Register</h1>
            <p className="text-gray-600 dark:text-gray-400 mt-1">
              Enter your details below to create your account
            </p>
          </div>

          <form onSubmit={submit}>
            {/* Full Name Input */}
            <div className="mb-4">
              <Label htmlFor="name" className="mb-2">
                Full Name
              </Label>
              <Input
                id="name"
                type="text"
                name="name"
                value={data.name}
                autoComplete="name"
                placeholder="Full Name"
                onChange={(e) => setData('name', e.target.value)}
                required
              />
              {errors.name && (
                <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.name}</p>
              )}
            </div>

            {/* Email Input */}
            <div className="mb-4">
              <Label htmlFor="email" className="mb-2">
                Email
              </Label>
              <Input
                id="email"
                type="email"
                name="email"
                value={data.email}
                autoComplete="username"
                placeholder="your@email.com"
                onChange={(e) => setData('email', e.target.value)}
                required
              />
              {errors.email && (
                <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.email}</p>
              )}
            </div>

            {/* Password Input */}
            <div className="mb-4">
              <Label htmlFor="password" className="mb-2">
                Password
              </Label>
              <Input
                id="password"
                type="password"
                name="password"
                value={data.password}
                autoComplete="new-password"
                placeholder="••••••••"
                onChange={(e) => setData('password', e.target.value)}
                required
              />
              {errors.password && (
                <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.password}</p>
              )}
            </div>

            {/* Confirm Password Input */}
            <div className="mb-4">
              <Label htmlFor="password_confirmation" className="mb-2">
                Confirm Password
              </Label>
              <Input
                id="password_confirmation"
                type="password"
                name="password_confirmation"
                value={data.password_confirmation}
                autoComplete="new-password"
                placeholder="••••••••"
                onChange={(e) => setData('password_confirmation', e.target.value)}
                required
              />
              {errors.password_confirmation && (
                <p className="mt-1 text-sm text-red-600 dark:text-red-400">{errors.password_confirmation}</p>
              )}
            </div>

            {/* Register Button */}
            <Button
              type="submit"
              disabled={processing}
              className="w-full"
            >
              {processing ? 'Creating Account...' : 'Create Account'}
            </Button>
          </form>

          {/* Login Link */}
          <div className="text-center mt-6">
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Already have an account?{' '}
              <Link
                href={login.url()}
                className="text-blue-600 dark:text-blue-400 hover:underline font-medium"
              >
                Sign in
              </Link>
            </p>
          </div>
        </div>
      </div>
    </AuthLayout>
  );
}
